# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:
  subscriptionid: '1de23ac9-6718-48d0-a988-63d2c566866f'
  deploymentlocation: 'westus2'

pool:
  vmImage: ubuntu-latest

stages:
  - stage: preDeploy
    jobs:
      - job: scanWhatif
        displayName: scan and run whatif
        pool:
          vmImage: windows-2022

        steps:
        
        
