trigger:
- none

pool: 'masvc_adoRunners'

variables: 
  - group: prodTableStorageVariables

stages:
  - stage: getClientList
    displayName: Gather current client list from AzTableStorage
    jobs:
      - job: getClientList
        displayName: Get client list from AzTableStorage
        steps:
        - task: AzurePowerShell@5
          name: getSubscriptions
          inputs:
            azureSubscription: 'Azure DevOps Connection - Multi Tenant Deployment'
            ScriptType: FilePath
            ScriptPath: '$(System.DefaultWorkingDirectory)/utilities/helperScripts/multiClientDeployment.ps1'
            ScriptArguments: -tableResourceGroup $(tableResourceGroup) -tableStorageAccount $(tableStorageAccount) -tableName $(tableName) -getClientListOnly
            azurePowerShellVersion: 'LatestVersion'
      - job: deployBackupStackTest
        displayName: Deploy Backup Stack Test
        dependsOn: getClientList
        steps:
        - task: AzurePowerShell@5
          name: deployBackupStackTest
          inputs:
            azureSubscription: 'Azure DevOps Connection - Multi Tenant Deployment'
            ScriptType: FilePath
            ScriptPath: '$(System.DefaultWorkingDirectory)/utilities/helperScripts/multiClientDeployment.ps1'
            ScriptArguments: -tableResourceGroup $(tableResourceGroup) -tableStorageAccount $(tableStorageAccount) -tableName $(tableName) -deploymentName "masvcAzMSP_BackupDeploymentStack" -bicepFilePath ".\solutions\backupOnboarding\main.bicep" -testDeploy $true
            azurePowerShellVersion: 'LatestVersion'
      - job: clientListApproval
        displayName: Approve client list
        dependsOn:
          - deployBackupStackTest
        pool: server
        condition: succeeded()
        steps:
        - task: ManualValidation@0
          timeoutInMinutes: 1440 # task times out in 1 day
          name: clientListApproval
          displayName: Approve client list
          inputs:
            notifyUsers: |
              itsecops@microageservices.com
            instructions: 'Please review the list of clients to be deployed to and approve or reject the deployment.'
            onTimeout: 'reject'
      - job: deployBackupStackProd
        displayName: Backup Stack Production Deployment
        dependsOn: clientListApproval
        steps:
        - task: AzurePowerShell@5
          name: deployBackupStackProd
          inputs:
            azureSubscription: 'Azure DevOps Connection - Multi Tenant Deployment'
            ScriptType: FilePath
            ScriptPath: '$(System.DefaultWorkingDirectory)/utilities/helperScripts/multiClientDeployment.ps1'
            ScriptArguments: -tableResourceGroup $(tableResourceGroup) -tableStorageAccount $(tableStorageAccount) -tableName $(tableName) -deploymentName "masvcAzMSP_BackupDeploymentStack" -bicepFilePath ".\solutions\backupOnboarding\main.bicep" -testDeploy $false
            azurePowerShellVersion: 'LatestVersion'
