trigger:
- none

pool: 'masvc_adoRunners'

stages:
  - stage: Deploy
    displayName: Deploy templates to tenants
    jobs:
      - job: uamiStack
        displayName: deploy bicep templates for MicroAge User Assigned Managed Identities Stack
        steps:
        - task: AzurePowerShell@5
          inputs:
            azureSubscription: 'Azure DevOps Connection - Multi Tenant Deployment'
            ScriptType: FilePath
            ScriptPath: '$(System.DefaultWorkingDirectory)/solutions/onboardingManagedIdentities/deploy.ps1'
            ScriptArguments: -deploymentName "masvcAzMSP_ManagedIdentitiesDeploymentStack" -testDeploy $false -verbose
            azurePowerShellVersion: 'LatestVersion'
      - job: monitoringStack
        timeoutInMinutes: 180
        dependsOn: uamiStack
        displayName: deploy bicep templates for Monitoring and Policy Stack
        steps:
        - task: AzurePowerShell@5
          inputs:
            azureSubscription: 'Azure DevOps Connection - Multi Tenant Deployment'
            ScriptType: FilePath
            ScriptPath: '$(System.DefaultWorkingDirectory)/solutions/monitorOnboarding/deploy.ps1'
            ScriptArguments: -deploymentName "masvcAzMSP_MonitoringDeploymentStack" -testDeploy $false -verbose
            azurePowerShellVersion: 'LatestVersion'