# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool: 'masvc_adoRunners'

stages:
  - stage: getClientList
    displayName: Gather current client list from AzTableStorage
    jobs:
      - job: getClientList
        displayName: Get client list from AzTableStorage
        steps:
        - task: AzurePowerShell@5
          name: getSubscriptions
          inputs:
            azureSubscription: 'Azure DevOps Connection - Multi Tenant Deployment'
            ScriptType: FilePath
            ScriptPath: '$(System.DefaultWorkingDirectory)/utilities/helperScripts/multiClientDeployment.ps1'
            ScriptArguments: -tableResourceGroup $(tableResourceGroup) -tableStorageAccount $(tableStorageAccount) -tableName $(tableName) -getClientListOnly
            azurePowerShellVersion: 'LatestVersion'
      - job: deployManagedIdentityStackTest
        displayName: Deploy Managed Identity Stack Test Deploy
        dependsOn: getClientList
        steps:
        - task: AzurePowerShell@5
          name: deployManagedIdentityStackTest
          inputs:
            azureSubscription: 'Azure DevOps Connection - Multi Tenant Deployment'
            ScriptType: FilePath
            ScriptPath: '$(System.DefaultWorkingDirectory)/utilities/helperScripts/multiClientDeployment.ps1'
            ScriptArguments: -tableResourceGroup $(tableResourceGroup) -tableStorageAccount $(tableStorageAccount) -tableName $(tableName) -deploymentName "masvcAzMSP_ManagedIdentitiesDeploymentStack" -bicepFilePath ".\solutions\monitorOnboarding\main.bicep" -testDeploy $true
            azurePowerShellVersion: 'LatestVersion'
      - job: deployMonitoringStackTest
        displayName: Deploy Monitoring Stack Test Deploy
        dependsOn: getClientList
        steps:
        - task: AzurePowerShell@5
          name: deployMonitoringStackTest
          inputs:
            azureSubscription: 'Azure DevOps Connection - Multi Tenant Deployment'
            ScriptType: FilePath
            ScriptPath: '$(System.DefaultWorkingDirectory)/utilities/helperScripts/multiClientDeployment.ps1'
            ScriptArguments: -tableResourceGroup $(tableResourceGroup) -tableStorageAccount $(tableStorageAccount) -tableName $(tableName) -deploymentName "masvcAzMSP_MonitoringDeploymentStack" -bicepFilePath ".\solutions\monitorOnboarding\main.bicep" -testDeploy $true
            azurePowerShellVersion: 'LatestVersion'
      - job: clientListApproval
        displayName: Approve client list
        dependsOn:
          - deployManagedIdentityStackTest
          - deployMonitoringStackTest
        pool: server
        condition: succeeded()
        steps:
        - task: ManualValidation@0
          timeoutInMinutes: 1440 # task times out in 1 day
          name: clientListApproval
          displayName: Approve client list
          inputs:
            notifyUsers: |
              itsecops@microageservices.com
            instructions: 'Please review the list of clients to be deployed to and approve or reject the deployment.'
            onTimeout: 'reject'
      - job: deployManagedIdentityStackProd
        displayName: Deploy Managed Identity Stack Production Deployment
        dependsOn: clientListApproval
        steps:
        - task: AzurePowerShell@5
          name: deployManagedIdentityStackProd
          inputs:
            azureSubscription: 'Azure DevOps Connection - Multi Tenant Deployment'
            ScriptType: FilePath
            ScriptPath: '$(System.DefaultWorkingDirectory)/utilities/helperScripts/multiClientDeployment.ps1'
            ScriptArguments: -tableResourceGroup $(tableResourceGroup) -tableStorageAccount $(tableStorageAccount) -tableName $(tableName) -deploymentName "masvcAzMSP_ManagedIdentitiesDeploymentStack" -bicepFilePath ".\solutions\managedIdentityOnboarding\main.bicep" -testDeploy $false -noClientCode
            azurePowerShellVersion: 'LatestVersion'
      - job: deployMonitoringProd
        displayName: Deploy Monitoring Stack Production Deployment
        dependsOn:
          - clientListApproval
          - deployManagedIdentityStackProd
        steps:
        - task: AzurePowerShell@5
          name: deployMonitoringStackProd
          inputs:
            azureSubscription: 'Azure DevOps Connection - Multi Tenant Deployment'
            ScriptType: FilePath
            ScriptPath: '$(System.DefaultWorkingDirectory)/utilities/helperScripts/multiClientDeployment.ps1'
            ScriptArguments: -tableResourceGroup $(tableResourceGroup) -tableStorageAccount $(tableStorageAccount) -tableName $(tableName) -deploymentName "masvcAzMSP_MonitoringDeploymentStack" -bicepFilePath ".\solutions\monitorOnboarding\main.bicep" -testDeploy $false
            azurePowerShellVersion: 'LatestVersion'
            
