# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: windows-latest

stages:
  - stage: logAnalytics
    displayName: Deploy Log Analytics Workspace
    jobs:
      - job: logAnalyticsBicep
        displayName: Deploy logAnalytics Bicep Template
        steps:
        - task: AzurePowerShell@5
          inputs:
            azureSubscription: 'Azure DevOps Connection - Multi Tenant Deployment'
            ScriptType: 'FilePath'
            ScriptPath: '$(System.DefaultWorkingDirectory)/modules/operational-insights/workspaces/deploy.ps1'
            azurePowerShellVersion: 'LatestVersion'