# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool: 'masvc_adoRunners'

stages:
  - stage: getClientList
    displayName: Gather current client list from AzTableStorage
    jobs:
      - job: getClientList
        displayName: Get client list from AzTableStorage
        steps:
        - task: AzurePowerShell@5
          inputs:
            azureSubscription: 'Azure DevOps Connection - Multi Tenant Deployment'
            ScriptType: FilePath
            ScriptPath: '$(System.DefaultWorkingDirectory)/utilities/helperScripts/getClientSubscriptions.ps1'
            ScriptArguments: -tableResourceGroup "masvc-lighthouseAutomation-rg" -tableStorageAccount "masvclighthousetables001" -tableName "azMSPClients"
            azurePowerShellVersion: 'LatestVersion'
        - task: AzurePowerShell@5
          inputs:
            azureSubscription: 'Azure DevOps Connection - Multi Tenant Deployment'
            ScriptType: InlineScript
            Inline: |
              #Testing to see if we can read the output variable from the previous step
              Write-Host "Trying to Read" $(currentSubscriptions)
            azurePowerShellVersion: 'LatestVersion'
  - stage: Deploy
    displayName: Deploy templates to tenants
    jobs:
    - deployment: uamiStack
      displayName: deploy bicep templates for MicroAge User Assigned Managed Identities Stack
      environment: 'azMSPLighthouseProd'
      strategy:
        runOnce:
          deploy:
            steps:
             - checkout: self
             - task: AzurePowerShell@5
               inputs:
                azureSubscription: 'Azure DevOps Connection - Multi Tenant Deployment'
                ScriptType: FilePath
                ScriptPath: '$(System.DefaultWorkingDirectory)/utilities/helperScripts/multiClientDeployment.ps1'
                ScriptArguments: -deploymentName "masvcAzMSP_ManagedIdentitiesDeploymentStack" -testDeploy $true -verbose -clientSubscriptions '$(currentSubscriptions)' -bicepFilePath ".\solutions\monitorOnboarding\main.bicep"
                azurePowerShellVersion: 'LatestVersion'
    - deployment: monitoringStack
      dependsOn: uamiStack
      displayName: deploy bicep templates for MicroAge Monitoring Stack
      environment: 'azMSPLighthouseProd'
      strategy:
        runOnce:
          deploy:
            steps:
             - checkout: self
             - task: AzurePowerShell@5
               inputs:
                azureSubscription: 'Azure DevOps Connection - Multi Tenant Deployment'
                ScriptType: FilePath
                ScriptPath: '$(System.DefaultWorkingDirectory)/utilities/helperScripts/multiClientDeployment.ps1'
                ScriptArguments: -deploymentName "masvcAzMSP_MonitoringDeploymentStack" -testDeploy $true -verbose -clientSubscriptions '$(currentSubscriptions)' -bicepFilePath ".\solutions\monitorOnboarding\main.bicep"
                azurePowerShellVersion: 'LatestVersion'
