# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool: 'masvc_adoRunners'

parameters:
  - name: 'tableResourceGroup'
    type: string
    value: 'masvc-lighthouseAutomation-rg'

  - name: 'tableStorageAccount'
    type: string
    value: 'masvclighthousetables001'

  - name: 'tableName'
    type: string
    value: 'azMSPClients'

stages:
  - stage: getClientList
    displayName: Gather current client list from AzTableStorage
    jobs:
      - job: getClientList
        displayName: Get client list from AzTableStorage
        steps:
        - task: AzurePowerShell@5
          name: getSubscriptions
          inputs:
            azureSubscription: 'Azure DevOps Connection - Multi Tenant Deployment'
            ScriptType: FilePath
            ScriptPath: '$(System.DefaultWorkingDirectory)/utilities/helperScripts/multiClientDeployment.ps1'
            ScriptArguments: -tableResourceGroup ${{parameters.tableResourceGroup}} -tableStorageAccount ${{parameters.tableStorageAccount}} -tableName ${{parameters.tableName}} -getClientListOnly
            azurePowerShellVersion: 'LatestVersion'

            
