trigger:
- none

pool: 'masvc_vmsagentspool1'

stages:
  - stage: preDeploy
    displayName: test deployment for errors
    jobs:
      - job: deploymentWhatIf
        displayName: whatIf Run
        steps:
        - task: AzurePowerShell@5
          inputs:
            azureSubscription: 'Azure DevOps Connection - Multi Tenant Deployment'
            ScriptType: 'FilePath'
            ScriptPath: '$(System.DefaultWorkingDirectory)/solutions/monitorOnboarding/deploy_stackTesting.ps1'
            ScriptArguments: '-testDeploy $true -verbose'
            azurePowerShellVersion: 'LatestVersion'
  - stage: Deploy
    displayName: Deploy templates to tenants
    jobs:
      - job: deployment
        displayName: deploy bicep templates
        steps:
        - task: AzurePowerShell@5
          inputs:
            azureSubscription: 'Azure DevOps Connection - Multi Tenant Deployment'
            ScriptType: FilePath
            ScriptPath: '$(System.DefaultWorkingDirectory)/solutions/monitorOnboarding/deploy_stackTesting.ps1'
            ScriptArguments: '-testDeploy $false -verbose' 
            azurePowerShellVersion: 'LatestVersion'
