# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

resources:
  pipelines:
    - pipeline: onboardingPipeline #Name of the pipeline resource
      source: lighthouseOnboard - monitoring #Name of the pipeline referenced by this pipeline resource
      trigger:
        branches:
          include:
          - main

pool: 'masvc_adoRunners'

jobs:
  - job: remediatePolicy
    displayName: 'Remediate Policy'
    steps:
    - task: AzurePowerShell@5
      displayName: 'PowerShell script to run remediation Workflow'
      inputs:
        azureSubscription: 'Azure DevOps Connection - Multi Tenant Deployment'
        ScriptType: FilePath
        ScriptPath: '$(System.DefaultWorkingDirectory)/utilities/helperScripts/remediatePolicies.ps1'
        ScriptArguments: -policyName "$(policyName)"
        azurePowerShellVersion: 'LatestVersion'
        